
version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redisCache
    ports:
      - "6379"
  scrap:
    build: ./
    image: agnelrdx/scrap
    container_name: scrap
    depends_on:
      - redis
    links: 
      - redis
    command: 'npm start'