name: Deploy EC2
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH }}
          name: id_rsa
          known_hosts: "ec2-35-83-94-112.us-west-2.compute.amazonaws.com"
      - name: rsync over ssh
        run: ./deploy_to_aws.sh
